# Generated by Django 4.0.6 on 2022-11-30 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_ha', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'CAMPO',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CULTIVO',
            },
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('longitud', models.DecimalField(decimal_places=3, max_digits=10)),
                ('latitud', models.DecimalField(decimal_places=3, max_digits=10)),
                ('campo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cultivos.campo')),
            ],
            options={
                'verbose_name_plural': 'Localizaciones',
                'db_table': 'LOCALIZACION',
            },
        ),
        migrations.AddField(
            model_name='campo',
            name='CULTIVOS',
            field=models.ManyToManyField(to='cultivos.cultivo'),
        ),
        migrations.AddField(
            model_name='campo',
            name='login_agricultor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.agricultor'),
        ),
    ]
