# Generated by Django 4.0.6 on 2023-01-04 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agricultores',
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_ha', models.DecimalField(decimal_places=5, max_digits=12)),
                ('volumen_agua_disp', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('tipo_riego', models.CharField(choices=[('RSUPERFICIE', 'Riego por superficie'), ('RASPERSION', 'Riego por aspersión'), ('RLOCALIZADO', 'Riego localizado'), ('RSUBTERRANEO', 'Riego subterráneo')], default='RSUPERFICIE', max_length=255)),
            ],
            options={
                'db_table': 'CAMPO',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('precio_kg', models.DecimalField(decimal_places=5, max_digits=12)),
                ('riego_dia', models.DecimalField(decimal_places=5, max_digits=12)),
                ('tipo', models.CharField(choices=[('REGADIO', 'Cultivo de regadío'), ('SECANO', 'Cultivo de secano')], default='REGADIO', max_length=255)),
            ],
            options={
                'db_table': 'CULTIVO',
            },
        ),
        migrations.CreateModel(
            name='CultivoBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='cultivo/bulkupload/')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('longitud', models.DecimalField(decimal_places=5, max_digits=12)),
                ('latitud', models.DecimalField(decimal_places=5, max_digits=12)),
                ('campo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cultivos.campo')),
            ],
            options={
                'verbose_name_plural': 'Localizaciones',
                'db_table': 'LOCALIZACION',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCultivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campanya_sembrado', models.DecimalField(decimal_places=0, max_digits=4)),
                ('ha_sembradas', models.DecimalField(decimal_places=5, max_digits=12)),
                ('ha_cosechadas', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('produccion', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('rendimiento', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.campo')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
            options={
                'db_table': 'HISTORICO_CULTIVO',
                'unique_together': {('cultivo', 'campo', 'campanya_sembrado')},
            },
        ),
        migrations.CreateModel(
            name='CultivosCampo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campanya_sembrado', models.DecimalField(decimal_places=0, max_digits=4)),
                ('ha_sembradas', models.DecimalField(decimal_places=5, max_digits=12)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.campo')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
            options={
                'db_table': 'CULTIVOS_CAMPO',
                'unique_together': {('cultivo', 'campo', 'campanya_sembrado')},
            },
        ),
        migrations.AddField(
            model_name='campo',
            name='CULTIVOS',
            field=models.ManyToManyField(related_name='Cultivos', through='cultivos.CultivosCampo', to='cultivos.cultivo'),
        ),
        migrations.AddField(
            model_name='campo',
            name='HISTORICO_CULTIVO',
            field=models.ManyToManyField(related_name='Historico', through='cultivos.HistoricoCultivo', to='cultivos.cultivo'),
        ),
        migrations.AddField(
            model_name='campo',
            name='login_agricultor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.agricultor'),
        ),
    ]
