# Generated by Django 4.0.6 on 2022-12-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agricultor',
            options={'verbose_name_plural': 'Agricultores'},
        ),
        migrations.RenameField(
            model_name='agricultor',
            old_name='nombre',
            new_name='email',
        ),
    ]
