# Generated by Django 4.0.6 on 2023-01-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='num_ha',
            field=models.DecimalField(decimal_places=5, max_digits=17),
        ),
        migrations.AlterField(
            model_name='campo',
            name='volumen_agua_disp',
            field=models.DecimalField(decimal_places=5, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='precio_kg',
            field=models.DecimalField(decimal_places=5, max_digits=17),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='riego_dia',
            field=models.DecimalField(decimal_places=5, max_digits=17),
        ),
        migrations.AlterField(
            model_name='cultivoscampo',
            name='ha_sembradas',
            field=models.DecimalField(decimal_places=5, max_digits=17),
        ),
        migrations.AlterField(
            model_name='historicocultivo',
            name='ha_cosechadas',
            field=models.DecimalField(decimal_places=5, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='historicocultivo',
            name='ha_sembradas',
            field=models.DecimalField(decimal_places=5, max_digits=17),
        ),
        migrations.AlterField(
            model_name='historicocultivo',
            name='produccion',
            field=models.DecimalField(decimal_places=5, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='historicocultivo',
            name='rendimiento',
            field=models.DecimalField(decimal_places=5, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='latitud',
            field=models.DecimalField(decimal_places=5, max_digits=17),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='longitud',
            field=models.DecimalField(decimal_places=5, max_digits=17),
        ),
    ]
